import {
  SiGooglecalendar,
  SiGmail,
  SiGooglesheets,
  SiGoogledrive,
  SiGoogledocs,
  SiSlack,
  SiGithub,
  SiNotion,
  SiTrello,
  SiLinear,
  SiJira,
  SiHubspot,
  SiSalesforce,
  SiDiscord,
  SiZoom,
  SiStripe,
  SiAirtable,
  SiAsana,
  SiShopify,
  SiDropbox,
  SiFigma,
  SiZendesk,
  SiInstagram,
  SiX,
} from "react-icons/si";

import type { Category, Integration } from "./types";

export const CATEGORIES: Category[] = [
  "Todos",
  "Productividad",
  "Comunicación",
  "Desarrollo",
  "CRM",
  "Redes Sociales",
  "Finanzas",
];

export const INTEGRATIONS: Integration[] = [
  { id: "googlecalendar", name: "Google Calendar", description: "Crea y gestiona eventos en tu calendario",        category: "Productividad",   icon: SiGooglecalendar, color: "#4285F4" },
  { id: "gmail",          name: "Gmail",           description: "Lee y envía correos electrónicos",               category: "Comunicación",    icon: SiGmail,          color: "#EA4335" },
  { id: "googlesheets",   name: "Google Sheets",   description: "Lee y edita hojas de cálculo",                   category: "Productividad",   icon: SiGooglesheets,   color: "#34A853" },
  { id: "googledrive",    name: "Google Drive",    description: "Accedé y organizá archivos en la nube",          category: "Productividad",   icon: SiGoogledrive,    color: "#4285F4" },
  { id: "googledocs",     name: "Google Docs",     description: "Creá y editá documentos de texto",               category: "Productividad",   icon: SiGoogledocs,     color: "#4285F4" },
  { id: "slack",          name: "Slack",           description: "Enviá mensajes y notificaciones a canales",      category: "Comunicación",    icon: SiSlack,          color: "#4A154B" },
  { id: "github",         name: "GitHub",          description: "Gestioná repositorios, issues y pull requests",  category: "Desarrollo",      icon: SiGithub,         color: "#181717" },
  { id: "notion",         name: "Notion",          description: "Creá páginas y bases de datos",                  category: "Productividad",   icon: SiNotion,         color: "#000000" },
  { id: "trello",         name: "Trello",          description: "Administrá tableros y tarjetas de proyectos",    category: "Productividad",   icon: SiTrello,         color: "#0052CC" },
  { id: "linear",         name: "Linear",          description: "Gestioná issues y sprints de desarrollo",        category: "Desarrollo",      icon: SiLinear,         color: "#5E6AD2" },
  { id: "jira",           name: "Jira",            description: "Seguimiento de proyectos ágiles y bugs",         category: "Desarrollo",      icon: SiJira,           color: "#0052CC" },
  { id: "hubspot",        name: "HubSpot",         description: "Gestioná contactos y pipeline de ventas",        category: "CRM",             icon: SiHubspot,        color: "#FF7A59" },
  { id: "salesforce",     name: "Salesforce",      description: "CRM empresarial para ventas y clientes",         category: "CRM",             icon: SiSalesforce,     color: "#00A1E0" },
  { id: "twitter",        name: "Twitter / X",     description: "Publicá tweets y gestioná tu cuenta",           category: "Redes Sociales",  icon: SiX,              color: "#000000" },
  { id: "linkedin",       name: "LinkedIn",        description: "Publicá y gestioná tu perfil profesional",      category: "Redes Sociales",  icon: null,             color: "#0A66C2" },
  { id: "discord",        name: "Discord",         description: "Enviá mensajes a servidores y canales",          category: "Comunicación",    icon: SiDiscord,        color: "#5865F2" },
  { id: "zoom",           name: "Zoom",            description: "Crea y administrá reuniones de video",           category: "Comunicación",    icon: SiZoom,           color: "#2D8CFF" },
  { id: "stripe",         name: "Stripe",          description: "Gestioná pagos, cobros y suscripciones",         category: "Finanzas",        icon: SiStripe,         color: "#635BFF" },
  { id: "airtable",       name: "Airtable",        description: "Base de datos flexible para equipos",            category: "Productividad",   icon: SiAirtable,       color: "#18BFFF" },
  { id: "asana",          name: "Asana",           description: "Gestioná tareas y proyectos de tu equipo",       category: "Productividad",   icon: SiAsana,          color: "#F06A6A" },
  { id: "shopify",        name: "Shopify",         description: "Administrá tu tienda y pedidos en línea",        category: "Finanzas",        icon: SiShopify,        color: "#96BF48" },
  { id: "dropbox",        name: "Dropbox",         description: "Accedé y compartí archivos en la nube",          category: "Productividad",   icon: SiDropbox,        color: "#0061FF" },
  { id: "figma",          name: "Figma",           description: "Colaborá en diseños y prototipos",               category: "Desarrollo",      icon: SiFigma,          color: "#F24E1E" },
  { id: "microsoftteams", name: "Microsoft Teams", description: "Chateá y realizá reuniones en Teams",            category: "Comunicación",    icon: null,             color: "#6264A7" },
  { id: "zendesk",        name: "Zendesk",         description: "Gestioná tickets y soporte al cliente",          category: "CRM",             icon: SiZendesk,        color: "#03363D" },
  { id: "pipedrive",      name: "Pipedrive",       description: "CRM orientado a ventas y seguimiento de leads",  category: "CRM",             icon: null,             color: "#017737" },
  { id: "instagram",      name: "Instagram",       description: "Publicá contenido y gestioná tu cuenta",         category: "Redes Sociales",  icon: SiInstagram,      color: "#E4405F" },
];
